{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-station.fullname" . }}-redis
  labels:
    {{- include "nexus-station.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "nexus-station.componentSelectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
{{- end }}
