{{- if .Values.crewService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-station.fullname" . }}-crew-service
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: crew-service
spec:
  replicas: {{ .Values.crewService.replicaCount }}
  revisionHistoryLimit: {{ .Values.crewService.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.crewService.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nexus-station.selectorLabels" (dict "context" . "component" "crew-service") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus-station.selectorLabels" (dict "context" . "component" "crew-service") | nindent 8 }}
        {{- with .Values.crewService.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.crewService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "nexus-station.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: crew-service
          image: {{ include "nexus-station.image" (dict "context" . "image" .Values.crewService.image) | quote }}
          imagePullPolicy: {{ .Values.crewService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.crewService.service.containerPort }}
              protocol: TCP
          {{- with .Values.crewService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.crewService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: "crew-service"
            {{- include "nexus-station.commonEnv" . | nindent 12 }}
            {{- include "nexus-station.otelEnv" . | nindent 12 }}
            {{- include "nexus-station.chaosEnv" (dict "context" . "serviceOverride" .Values.chaos.crew) | nindent 12 }}
            - name: SERVICES_LIFE_SUPPORT_URL
              value: "http://{{ include "nexus-station.fullname" . }}-life-support-service:{{ .Values.lifeSupportService.service.port }}"
            {{- with .Values.crewService.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.crewService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
