apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-station.fullname" . }}-cortex
  labels:
    {{- include "nexus-station.componentLabels" (dict "root" . "component" "cortex") | nindent 4 }}
spec:
  type: {{ .Values.cortex.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.cortex.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.cortex.service.type "NodePort") .Values.cortex.service.nodePort }}
      nodePort: {{ .Values.cortex.service.nodePort }}
      {{- end }}
  selector:
    {{- include "nexus-station.componentSelectorLabels" (dict "root" . "component" "cortex") | nindent 4 }}
