{{- if .Values.lifeSupportService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-station.fullname" . }}-life-support-service
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: life-support-service
spec:
  replicas: {{ .Values.lifeSupportService.replicaCount }}
  revisionHistoryLimit: {{ .Values.lifeSupportService.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.lifeSupportService.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nexus-station.selectorLabels" (dict "context" . "component" "life-support-service") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus-station.selectorLabels" (dict "context" . "component" "life-support-service") | nindent 8 }}
        {{- with .Values.lifeSupportService.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.lifeSupportService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "nexus-station.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: life-support-service
          image: {{ include "nexus-station.image" (dict "context" . "image" .Values.lifeSupportService.image) | quote }}
          imagePullPolicy: {{ .Values.lifeSupportService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.lifeSupportService.service.containerPort }}
              protocol: TCP
          {{- with .Values.lifeSupportService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.lifeSupportService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: "life-support-service"
            {{- include "nexus-station.commonEnv" . | nindent 12 }}
            {{- include "nexus-station.otelEnv" . | nindent 12 }}
            {{- include "nexus-station.chaosEnv" (dict "context" . "serviceOverride" .Values.chaos.lifeSupport) | nindent 12 }}
            - name: SERVICES_POWER_URL
              value: "http://{{ include "nexus-station.fullname" . }}-power-service:{{ .Values.powerService.service.port }}"
            {{- with .Values.lifeSupportService.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.lifeSupportService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
