{{- if .Values.inventoryService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-station.fullname" . }}-inventory-service
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: inventory-service
spec:
  type: {{ .Values.inventoryService.service.type }}
  ports:
    - port: {{ .Values.inventoryService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nexus-station.selectorLabels" (dict "context" . "component" "inventory-service") | nindent 4 }}
{{- end }}
