{{- if .Values.powerService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-station.fullname" . }}-power-service
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: power-service
spec:
  replicas: {{ .Values.powerService.replicaCount }}
  revisionHistoryLimit: {{ .Values.powerService.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.powerService.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nexus-station.selectorLabels" (dict "context" . "component" "power-service") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus-station.selectorLabels" (dict "context" . "component" "power-service") | nindent 8 }}
        {{- with .Values.powerService.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.powerService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "nexus-station.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: power-service
          image: {{ include "nexus-station.image" (dict "context" . "image" .Values.powerService.image) | quote }}
          imagePullPolicy: {{ .Values.powerService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.powerService.service.containerPort }}
              protocol: TCP
          {{- with .Values.powerService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.powerService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: "power-service"
            {{- include "nexus-station.commonEnv" . | nindent 12 }}
            {{- include "nexus-station.otelEnv" . | nindent 12 }}
            {{- with .Values.powerService.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.powerService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
