{{- if .Values.powerService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-station.fullname" . }}-power-service
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: power-service
spec:
  type: {{ .Values.powerService.service.type }}
  ports:
    - port: {{ .Values.powerService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nexus-station.selectorLabels" (dict "context" . "component" "power-service") | nindent 4 }}
{{- end }}
