apiVersion: apps/v1
kind: Deployment
metadata:
  name: crew
  labels:
    {{- include "nexus-crew.labels" . | nindent 4 }}
    app.kubernetes.io/component: crew
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nexus-crew.selectorLabels" (dict "context" . "component" "crew") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus-crew.selectorLabels" (dict "context" . "component" "crew") | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "nexus-crew.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: crew
          image: {{ include "nexus-crew.image" (dict "context" . "image" .Values.image) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: "crew-service"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: {{ .Values.database.schema | quote }}
            {{- include "nexus-common.loggingEnv" . | nindent 12 }}
            {{- include "nexus-common.podEnv" . | nindent 12 }}
            {{- include "nexus-common.databaseEnv" . | nindent 12 }}
            {{- include "nexus-common.redisEnv" . | nindent 12 }}
            {{- include "nexus-common.otelEnv" . | nindent 12 }}
            {{- include "nexus-common.chaosEnv" . | nindent 12 }}
            - name: SERVICES_LIFE_SUPPORT_URL
              value: {{ include "nexus-crew.lifeSupportUrl" . | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
