apiVersion: v2
name: nexus-station
description: A Helm chart for deploying NEXUS Station microservices to Kubernetes
type: application
version: 0.0.0-dev
appVersion: ""
sources:
  - https://github.com/maxanderson95/nexus
maintainers:
  - name: Max Anderson
