{{- if .Values.loadGenerator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-station.fullname" . }}-load-generator
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nexus-station.selectorLabels" (dict "context" . "component" "load-generator") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus-station.selectorLabels" (dict "context" . "component" "load-generator") | nindent 8 }}
    spec:
      {{- include "nexus-station.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: load-generator
          image: {{ include "nexus-station.image" (dict "context" . "image" .Values.loadGenerator.image) | quote }}
          imagePullPolicy: {{ .Values.loadGenerator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.loadGenerator.service.containerPort }}
              protocol: TCP
          env:
            - name: LOCUST_HOST
              value: "http://{{ include "nexus-station.fullname" . }}-cortex:{{ .Values.cortex.service.port }}"
            - name: LOCUST_USERS
              value: {{ .Values.loadGenerator.users | quote }}
            - name: LOCUST_SPAWN_RATE
              value: {{ .Values.loadGenerator.spawnRate | quote }}
            {{- include "nexus-station.otelEnv" . | nindent 12 }}
          {{- with .Values.loadGenerator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
