{{- if .Values.loadGenerator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-station.fullname" . }}-load-generator
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: load-generator
spec:
  type: {{ .Values.loadGenerator.service.type }}
  ports:
    - port: {{ .Values.loadGenerator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nexus-station.selectorLabels" (dict "context" . "component" "load-generator") | nindent 4 }}
{{- end }}
