{{- if .Values.cortex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-station.fullname" . }}-cortex
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: cortex
spec:
  type: {{ .Values.cortex.service.type }}
  ports:
    - port: {{ .Values.cortex.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nexus-station.selectorLabels" (dict "context" . "component" "cortex") | nindent 4 }}
{{- end }}
