{{- if .Values.dockingService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-station.fullname" . }}-docking-service
  labels:
    {{- include "nexus-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: docking-service
spec:
  replicas: {{ .Values.dockingService.replicaCount }}
  revisionHistoryLimit: {{ .Values.dockingService.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.dockingService.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nexus-station.selectorLabels" (dict "context" . "component" "docking-service") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus-station.selectorLabels" (dict "context" . "component" "docking-service") | nindent 8 }}
        {{- with .Values.dockingService.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.dockingService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "nexus-station.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: docking-service
          image: {{ include "nexus-station.image" (dict "context" . "image" .Values.dockingService.image) | quote }}
          imagePullPolicy: {{ .Values.dockingService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.dockingService.service.containerPort }}
              protocol: TCP
          {{- with .Values.dockingService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dockingService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: "docking-service"
            - name: OTEL_SERVICE_NAME
              value: "docking-service"
            {{- include "nexus-station.commonEnv" . | nindent 12 }}
            {{- include "nexus-station.otelEnv" . | nindent 12 }}
            {{- with .Values.dockingService.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.dockingService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
