apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex
  labels:
    {{- include "nexus-cortex.labels" . | nindent 4 }}
    app.kubernetes.io/component: cortex
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nexus-cortex.selectorLabels" (dict "context" . "component" "cortex") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus-cortex.selectorLabels" (dict "context" . "component" "cortex") | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "nexus-cortex.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: cortex
          image: {{ include "nexus-cortex.image" (dict "context" . "image" .Values.image) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: "cortex"
            {{- include "nexus-common.loggingEnv" . | nindent 12 }}
            {{- include "nexus-common.podEnv" . | nindent 12 }}
            {{- include "nexus-common.redisEnv" . | nindent 12 }}
            {{- include "nexus-common.otelEnv" . | nindent 12 }}
            {{- include "nexus-common.chaosEnv" . | nindent 12 }}
            - name: SERVICES_POWER_URL
              value: {{ include "nexus-cortex.powerUrl" . | quote }}
            - name: SERVICES_LIFE_SUPPORT_URL
              value: {{ include "nexus-cortex.lifeSupportUrl" . | quote }}
            - name: SERVICES_CREW_URL
              value: {{ include "nexus-cortex.crewUrl" . | quote }}
            - name: SERVICES_DOCKING_URL
              value: {{ include "nexus-cortex.dockingUrl" . | quote }}
            - name: SERVICES_INVENTORY_URL
              value: {{ include "nexus-cortex.inventoryUrl" . | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
